/*******************************

This file is automatically generated by build.py based on utils.mjs
If you need something on utils.js, edit utils.mjs instead

*********************************/

console.error(`
This file is automatically generated by build.py based on utils.mjs
If you need something on utils.js, edit utils.mjs instead
`)
throw `
This file is automatically generated by build.py based on utils.mjs
If you need something on utils.js, edit utils.mjs instead
`
